= Configure and Populate a Directory Server
:imagesdir: ../images/
:source-highlighter: rouge
:icons: font


== Introduction

Take 1-3 sentences to introduce the module. Put it into context within the larger course narrative.


== Lecture

=== Slide

Helpful image here

---
* Give 1-2 slides about the subject of the module
* Don't be tempted to explain everything -- just enough so that the student can be successful in the activity
* Should be image-driven, not text-driven



== Activity

Write a short introduction to the activity. Clearly state the purpose. There can be many kinds of activities, including:

* A hands-on lab inside a VM (probably the most common)
** could include challenges with hints
** prompt students to predict and verify
* A worksheet
* Research a documentation page and answer a set of questions
* Reflect on learning with a "3, 2, 1"
** 3 things you learned
** 2 things you found interesting
** one question you still have (take it to the forum and discuss)
* Draw a picture and discuss in the forum
* Analyze a fictional discussion for misconceptions, e.g.:
** “Donald and Mukta wanted to get result Z. Donald did X because reasons. Mukta did Y because reasons. Do you agree with either of them? Explain your reasoning”

Remember again https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/#:~:text=Familiarly%20known%20as%20Bloom's%20Taxonomy,Analysis%2C%20Synthesis%2C%20and%20Evaluation[Bloom's Taxonomy of Educational Objectives] to evoke different kinds and levels of thinking.

=== Part 1

. Do a thing:
+
[source,bash]
----
./code_n_stuff
----


== Activity Debrief

* Include key takeaways/gotchas from the activities
** Can be in the form of discussion questions with sample responses given in collapsible blocks
* Can be an illustrative slide or two
* Can be some quick bullet points or code snippets

== Summary

Return to the purpose of the activity. Put this back in context with where we are in the learning story. Transition to the next module.

=== References

* Some links to relevant blog posts, whitepapers, docs, presentations, and other resources
* Make sure to use a `^` at the end to ensure the link opens in a new tab. See https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro-attribute-parsing/#blank-window-shorthand[attribute parsing^]